imports:
  - { resource: ../common_services.yml }

services:
  Spark\EParagony\SupplementaryAdmin\AdminOrderDisplay:
    class: Spark\EParagony\SupplementaryAdmin\AdminOrderDisplay
    arguments:
      - '@twig'
      - '@router'
      - '@Spark\EParagony\DocumentsManager'
