services:
  _defaults:
    public: true

  Spark\EParagony\AddressChecker:
    class: Spark\EParagony\AddressChecker

  Spark\EParagony\CartPreferenceManager:
    class: Spark\EParagony\CartPreferenceManager
    arguments:
      - '@doctrine.orm.entity_manager'

  Spark\EParagony\ConfigHelper:
    class: Spark\EParagony\ConfigHelper

  Spark\EParagony\Controller\AdminMailerController:
    class: Spark\EParagony\Controller\AdminMailerController
    arguments:
      - '@Spark\EParagony\Mailer'
      - '@Spark\EParagony\DocumentsManager'

  Spark\EParagony\Controller\AdminSpecialController:
    class: Spark\EParagony\Controller\AdminSpecialController
    arguments:
      - '@Spark\EParagony\DocumentsManager'

  Spark\EParagony\Controller\AdminTwigController:
    class: Spark\EParagony\Controller\AdminTwigController
    arguments:
      - '@Spark\EParagony\DocumentsManager'
      - '@Spark\EParagony\PrinterLogManager'

  Spark\EParagony\DocumentsManager:
    class: Spark\EParagony\DocumentsManager
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@Spark\EParagony\ReceiptQueueManager'
      - '@Spark\EParagony\Mailer'
      - '@Spark\EParagony\SparkApi\ApiSparkFactory'
      - '@Spark\EParagony\OrderChecker'

  Spark\EParagony\Mailer:
    class: Spark\EParagony\Mailer

  Spark\EParagony\MagicBox:
    class: Spark\EParagony\MagicBox

  Spark\EParagony\OrderChecker:
    class: Spark\EParagony\OrderChecker

  Spark\EParagony\PrinterLogManager:
    class: Spark\EParagony\PrinterLogManager
    arguments:
      - '@doctrine.orm.entity_manager'

  Spark\EParagony\PrintServer\PrintServerAction:
    class: Spark\EParagony\PrintServer\PrintServerAction
    arguments:
      - '@Spark\EParagony\PrintServer\PrintServerLogin'
      - '@Spark\EParagony\DocumentsManager'
      - '@Spark\EParagony\PrinterLogManager'

  Spark\EParagony\PrintServer\PrintServerLogin:
    class: Spark\EParagony\PrintServer\PrintServerLogin
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@Spark\EParagony\ConfigHelper'

  Spark\EParagony\ReceiptQueueManager:
    class: Spark\EParagony\ReceiptQueueManager
    arguments:
      - '@doctrine.orm.entity_manager'

  Spark\EParagony\SparkApi\ApiSparkFactory:
    class: Spark\EParagony\SparkApi\ApiSparkFactory
    arguments:
      - '@Spark\EParagony\ConfigHelper'
      - '@Spark\EParagony\MagicBox'
      - '%kernel.cache_dir%'

  Spark\EParagony\SparkApi\WebHookSpark:
    class: Spark\EParagony\SparkApi\WebHookSpark
    arguments:
      - '@Spark\EParagony\DocumentsManager'
      - '@Spark\EParagony\ConfigHelper'
      - '%kernel.cache_dir%'

  Spark\EParagony\SupplementaryFront\FrontAction:
    class: Spark\EParagony\SupplementaryFront\FrontAction
    arguments:
      - '@Spark\EParagony\CartPreferenceManager'

  Spark\EParagony\SupplementaryFront\FrontDisplaySupport:
    class: Spark\EParagony\SupplementaryFront\FrontDisplaySupport
    arguments:
      - '@Spark\EParagony\AddressChecker'
      - '@Spark\EParagony\ConfigHelper'
