eparagony_admin_debug_web_server:
  path: /eparagony/debug/web_server
  defaults:
    _controller: 'Spark\EParagony\Controller\AdminTwigController::debugWebServer'

eparagony_admin_force_download:
  path: /eparagony/force/download
  defaults:
    _controller: 'Spark\EParagony\Controller\AdminSpecialController::forceReceiptDownload'

eparagony_admin_mail_receipt:
  path: /eparagony/send/receipt
  defaults:
    _controller: 'Spark\EParagony\Controller\AdminMailerController::sendReceiptUrl'
