imports:
  - { resource: ./common.yml }

services:

  prestashop.module.createit_accordion.type.accordion:
    class: 'PrestaShop\Module\CreateitAccordion\Form\CreateitAccordionType'
    parent: 'form.type.translatable.aware'
    public: true
    arguments:
      - '@=service("prestashop.adapter.multistore_feature").isUsed()'
    tags:
      - { name: form.type }

  prestashop.module.createit_accordion.form.identifiable_object.data_provider.createit_accordion_form_data_provider:
    class: 'PrestaShop\Module\CreateitAccordion\Form\CreateitAccordionFormDataProvider'
    arguments:
      - '@prestashop.module.createit_accordion.createit_accordion_repository'

  prestashop.module.createit_accordion.form.identifiable_object.data_handler.createit_accordion_data_handler:
    class: 'PrestaShop\Module\CreateitAccordion\Form\CreateitAccordionFormDataHandler'
    arguments:
      - '@prestashop.module.createit_accordion.createit_accordion_repository'
      - '@prestashop.core.admin.lang.repository'
      - '@doctrine.orm.default_entity_manager'

  prestashop.module.createit_accordion.form.identifiable_object.handler.createit_accordion_form_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Handler\FormHandler'
    factory: 'prestashop.core.form.identifiable_object.handler.form_handler_factory:create'
    arguments:
      - '@prestashop.module.createit_accordion.form.identifiable_object.data_handler.createit_accordion_data_handler'

  prestashop.module.createit_accordion.form.identifiable_object.builder.createit_accordion_form_builder:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Builder\FormBuilder'
    factory: 'prestashop.core.form.builder.form_builder_factory:create'
    arguments:
      - 'PrestaShop\Module\CreateitAccordion\Form\CreateitAccordionType'
      - '@prestashop.module.createit_accordion.form.identifiable_object.data_provider.createit_accordion_form_data_provider'

  prestashop.module.createit_accordion.grid.query_builder.accordion:
    class: 'PrestaShop\Module\CreateitAccordion\Grid\Query\CreateitAccordionQueryBuilder'
    parent: 'prestashop.core.grid.abstract_query_builder'
    public: true
    arguments:
      - '@prestashop.core.query.doctrine_search_criteria_applicator'
      - "@=service('prestashop.adapter.legacy.context').getContext().language.id"

  prestashop.module.createit_accordion.grid.data_provider.accordion:
    class: '%prestashop.core.grid.data.factory.doctrine_grid_data_factory%'
    arguments:
      - '@prestashop.module.createit_accordion.grid.query_builder.accordion'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.core.grid.query.doctrine_query_parser'
      - 'createit_accordion'

  prestashop.module.createit_accordion.grid.definition.factory.accordion:
    class: 'PrestaShop\Module\CreateitAccordion\Grid\Definition\Factory\CreateitAccordionDefinitionFactory'
    parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
    public: true

  prestashop.module.createit_accordion.grid.factory.accordion:
    class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
    arguments:
      - '@prestashop.module.createit_accordion.grid.definition.factory.accordion'
      - '@prestashop.module.createit_accordion.grid.data_provider.accordion'
      - '@prestashop.core.grid.filter.form_factory'
      - '@prestashop.core.hook.dispatcher'