imports:
  - { resource: ./common.yml }

services:

  prestashop.module.createit_custom_field.grid.definition.factory.custom_fields:
    class: 'PrestaShop\Module\CreateITCustomField\Grid\Definition\Factory\CreateitCustomFieldDefinitionFactory'
    parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
    public: true

  prestashop.module.createit_custom_field.type.custom_fields:
    class: 'PrestaShop\Module\CreateITCustomField\Form\CreateitCustomFieldType'
    parent: 'form.type.translatable.aware'
    public: true
    arguments:
      - '@=service("prestashop.adapter.multistore_feature").isUsed()'
    tags:
      - { name: form.type }

  prestashop.module.createit_custom_field.form.identifiable_object.data_provider.createit_custom_field_data_provider:
    class: 'PrestaShop\Module\CreateITCustomField\Form\CreateitCustomFieldFormDataProvider'
    arguments:
      - '@prestashop.module.createit_custom_field.repository.custom_field_product_repository'

  prestashop.module.createit_custom_field.form.identifiable_object.data_handler.createit_custom_field_data_handler:
    class: 'PrestaShop\Module\CreateITCustomField\Form\CreateitCustomFieldFormDataHandler'
    arguments:
      - '@prestashop.module.createit_custom_field.repository.custom_field_product_repository'
      - '@doctrine.orm.default_entity_manager'

  prestashop.module.createit_custom_field.form.identifiable_object.handler.createit_custom_field_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Handler\FormHandler'
    factory: 'prestashop.core.form.identifiable_object.handler.form_handler_factory:create'
    arguments:
      - '@prestashop.module.createit_custom_field.form.identifiable_object.data_handler.createit_custom_field_data_handler'

  prestashop.module.createit_custom_field.form.identifiable_object.builder.createit_custom_field_form_builder:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Builder\FormBuilder'
    factory: 'prestashop.core.form.builder.form_builder_factory:create'
    arguments:
      - 'PrestaShop\Module\CreateITCustomField\Form\CreateitCustomFieldType'
      - '@prestashop.module.createit_custom_field.form.identifiable_object.data_provider.createit_custom_field_data_provider'

  prestashop.module.createit_custom_field.grid.factory.custom_fields:
    class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
    arguments:
      - '@prestashop.module.createit_custom_field.grid.definition.factory.custom_fields'
      - '@prestashop.module.createit_custom_field.grid.data_provider.custom_fields'
      - '@prestashop.core.grid.filter.form_factory'
      - '@prestashop.core.hook.dispatcher'

  prestashop.module.createit_custom_field.grid.data_provider.custom_fields:
    class: '%prestashop.core.grid.data.factory.doctrine_grid_data_factory%'
    arguments:
      - '@prestashop.module.createit_custom_field.grid.query_builder.custom_fields'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.core.grid.query.doctrine_query_parser'
      - 'createit_product_customfield'

  prestashop.module.createit_custom_field.grid.query_builder.custom_fields:
    class: 'PrestaShop\Module\CreateITCustomField\Grid\Query\CreateitCustomFieldQueryBuilder'
    parent: 'prestashop.core.grid.abstract_query_builder'
    public: true
    arguments:
      - '@prestashop.core.query.doctrine_search_criteria_applicator'
      - "@=service('prestashop.adapter.legacy.context').getContext().language.id"