imports:
  - { resource: ./common.yml }

services:

  prestashop.module.createit_countdown.type.countdown:
    class: 'PrestaShop\Module\CreateitCountdown\Form\CreateitCountdownFormFieldType'
    parent: 'form.type.translatable.aware'
    public: true
    arguments:
      - '@=service("prestashop.adapter.multistore_feature").isUsed()'
    tags:
      - { name: form.type }


